= Contributing

Feel free to improve this template.

== TODOs

- [ ] Represent in DDD: Sprint, Backlog, Sprint Backlog // UML Digram?
- [ ] Create grafic for Onion architecture
- [ ] Describe testing strategy (How, Why, When)
- [ ] Example for pushing data into EventStore (for all commands as example with middleware)
    - Add aggregate Root as example
- [ ] Example for pushing data into RabbitMq and returning Transaction/Correlation ID + Endpoint for pulling status of the job (Pseudo long running Job)
- [x] Use 'LoggingLevelSwitch' in 'Program.cs' to set Logging level based on configuration
- [ ] Write a better README with https://github.com/hackergrrl/art-of-readme
- [ ] Use Guid instead of int id (Protection) where possible
- [ ]

== Local testing

Local template install (osx, linux)
> dotnet new install ./

Local template install (Windows)
> dotnet new install .\

Find entry to uninstall
> dotnet new -u

Create example command (-n to provide new name of the solution)
> dotnet new ddd-webapi -n Magnus

== Local testing with docker

Build the container
> docker build -t tusk .

Run the container in dev mode
> docker run -p 5400:8080 -e CONNECTION_STRING=dummy -e ASPNETCORE_ENVIRONMENT=Development tusk

== Packing

Creating the nuget package
> nuget pack

Install the nuget package locally
> dotnet new install ./FJuette.Template.WebApi.4.1.1.nupkg

On _DateTimeOffset_ error:
> nuget locals all -clear

== Sources

- https://raw.githubusercontent.com/dotnet/roslyn/main/.editorconfig

DDD:
- DDD-Models: https://www.youtube.com/watch?v=fO2T5tRu3DE
- EF-Core part for this idea: https://www.youtube.com/watch?v=IGVRVO7KTss
- General Arch idea: https://www.youtube.com/watch?v=fe4iuaoxGbA